name: CI Pipeline - Pokedex

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish artefact
        run: eas update --auto